- key:               nxt-testnet
  name:              Nxt Testnet
  client:            nxt                              # API client name.
  server:            http://127.0.0.1:6876            # Public NXT node endpoint.
  height:            2024646                          # Initial block number from which sync will be started.
  min_confirmations: 1                                # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         https://test.nxtportal.org/accounts/#{address}
    transaction:     https://test.nxtportal.org/transactions/#{txid}
  status:            active
<% end %>
